package persistencia;
// Generated 18 abr. 2022 17:19:26 by Hibernate Tools 5.4.32.Final

/**
 * DatosEfaId generated by hbm2java
 */
public class DatosEfaId implements java.io.Serializable {

	private String nombre;
	private String direccion;
	private int codigoPostal;
	private int telefono;
	private int fax;
	private String paginaWeb;

	public DatosEfaId() {
	}

	public DatosEfaId(String nombre, String direccion, int codigoPostal, int telefono, int fax, String paginaWeb) {
		this.nombre = nombre;
		this.direccion = direccion;
		this.codigoPostal = codigoPostal;
		this.telefono = telefono;
		this.fax = fax;
		this.paginaWeb = paginaWeb;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public int getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(int codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	public int getTelefono() {
		return this.telefono;
	}

	public void setTelefono(int telefono) {
		this.telefono = telefono;
	}

	public int getFax() {
		return this.fax;
	}

	public void setFax(int fax) {
		this.fax = fax;
	}

	public String getPaginaWeb() {
		return this.paginaWeb;
	}

	public void setPaginaWeb(String paginaWeb) {
		this.paginaWeb = paginaWeb;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DatosEfaId))
			return false;
		DatosEfaId castOther = (DatosEfaId) other;

		return ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
				&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getDireccion() == castOther.getDireccion()) || (this.getDireccion() != null
						&& castOther.getDireccion() != null && this.getDireccion().equals(castOther.getDireccion())))
				&& (this.getCodigoPostal() == castOther.getCodigoPostal())
				&& (this.getTelefono() == castOther.getTelefono()) && (this.getFax() == castOther.getFax())
				&& ((this.getPaginaWeb() == castOther.getPaginaWeb()) || (this.getPaginaWeb() != null
						&& castOther.getPaginaWeb() != null && this.getPaginaWeb().equals(castOther.getPaginaWeb())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getDireccion() == null ? 0 : this.getDireccion().hashCode());
		result = 37 * result + this.getCodigoPostal();
		result = 37 * result + this.getTelefono();
		result = 37 * result + this.getFax();
		result = 37 * result + (getPaginaWeb() == null ? 0 : this.getPaginaWeb().hashCode());
		return result;
	}

}
