package persistencia;
// Generated 18 abr. 2022 17:19:26 by Hibernate Tools 5.4.32.Final

/**
 * DatosEfa generated by hbm2java
 */
public class DatosEfa implements java.io.Serializable {

	private DatosEfaId id;
	private Poblacion poblacion;

	public DatosEfa() {
	}

	public DatosEfa(DatosEfaId id, Poblacion poblacion) {
		this.id = id;
		this.poblacion = poblacion;
	}

	public DatosEfaId getId() {
		return this.id;
	}

	public void setId(DatosEfaId id) {
		this.id = id;
	}

	public Poblacion getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(Poblacion poblacion) {
		this.poblacion = poblacion;
	}

}
